export interface IPokemon {
    "_id": string,
    "Row"?: number,
    "Name": string,
    "Pokedex Number": number,
    "Img name": number,
    "Generation": string,
    "Evolution Stage"?: null,
    "Evolved": number,
    "FamilyID"?: null,
    "Cross Gen": number,
    "Type 1": string,
    "Type 2"?: string,
    "Weather 1": string,
    "Weather 2"?: string,
    "STAT TOTAL": number,
    "ATK": number,
    "DEF": number,
    "STA": number,
    "Legendary": number,
    "Aquireable": number,
    "Spawns": number,
    "Regional": number,
    "Raidable": number,
    "Hatchable": number,
    "Shiny": number,
    "Nest": number,
    "New": number,
    "Not-Gettable": number,
    "Future Evolve": number,
    "100% CP @ 40": number,
    "100% CP @ 39": number,
    "Description"?: string
}